// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u21516775_HW01_API.Models;

#nullable disable

namespace u21516775_HW01_API.Migrations
{
    [DbContext(typeof(AppDBcontext))]
    [Migration("20250402005227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u21516775_HW01_API.Models.ProductDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Comfortable running shoes for long distances.",
                            Price = 89.99m,
                            ProductName = "Running Shoes"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Noise-cancelling wireless headphones with long battery life.",
                            Price = 129.99m,
                            ProductName = "Wireless Headphones"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Fitness tracker and smartwatch with health monitoring features.",
                            Price = 199.99m,
                            ProductName = "Smartwatch"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Durable backpack with multiple compartments and laptop sleeve.",
                            Price = 49.99m,
                            ProductName = "Backpack"
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Insulated water bottle that keeps drinks cold for 24 hours.",
                            Price = 24.99m,
                            ProductName = "Water Bottle"
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Non-slip yoga mat with carrying strap.",
                            Price = 29.99m,
                            ProductName = "Yoga Mat"
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Whey protein powder with 25g protein per serving.",
                            Price = 39.99m,
                            ProductName = "Protein Powder"
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Set of 5 resistance bands with different strengths.",
                            Price = 19.99m,
                            ProductName = "Resistance Bands"
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Adjustable dumbbell set with various weight plates.",
                            Price = 149.99m,
                            ProductName = "Dumbbell Set"
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Simple fitness band that tracks steps, heart rate, and sleep.",
                            Price = 59.99m,
                            ProductName = "Fitness Tracker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
